services:
  vibesensor-server:
    build:
      context: .
      dockerfile: pi/Dockerfile
    environment:
      - VIBESENSOR_SERVE_STATIC=1
    network_mode: host
    volumes:
      - ./pi/data:/app/pi/data
    restart: unless-stopped
